//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumirClienteWS.ServiceReferenceCRUD {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCRUD.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/nuevo_cliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string nuevo_cliente(string nom_client, string dir_client, string tel_client, string email_client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/nuevo_cliente", ReplyAction="*")]
        System.Threading.Tasks.Task<string> nuevo_clienteAsync(string nom_client, string dir_client, string tel_client, string email_client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizar_cliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string actualizar_cliente(int id_client, string nom_client, string dir_client, string tel_client, string email_client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizar_cliente", ReplyAction="*")]
        System.Threading.Tasks.Task<string> actualizar_clienteAsync(int id_client, string nom_client, string dir_client, string tel_client, string email_client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminar_cliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string eliminar_cliente(int id_client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminar_cliente", ReplyAction="*")]
        System.Threading.Tasks.Task<string> eliminar_clienteAsync(int id_client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ver_cliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ver_cliente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ver_cliente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ver_clienteAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ConsumirClienteWS.ServiceReferenceCRUD.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ConsumirClienteWS.ServiceReferenceCRUD.WebService1Soap>, ConsumirClienteWS.ServiceReferenceCRUD.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string nuevo_cliente(string nom_client, string dir_client, string tel_client, string email_client) {
            return base.Channel.nuevo_cliente(nom_client, dir_client, tel_client, email_client);
        }
        
        public System.Threading.Tasks.Task<string> nuevo_clienteAsync(string nom_client, string dir_client, string tel_client, string email_client) {
            return base.Channel.nuevo_clienteAsync(nom_client, dir_client, tel_client, email_client);
        }
        
        public string actualizar_cliente(int id_client, string nom_client, string dir_client, string tel_client, string email_client) {
            return base.Channel.actualizar_cliente(id_client, nom_client, dir_client, tel_client, email_client);
        }
        
        public System.Threading.Tasks.Task<string> actualizar_clienteAsync(int id_client, string nom_client, string dir_client, string tel_client, string email_client) {
            return base.Channel.actualizar_clienteAsync(id_client, nom_client, dir_client, tel_client, email_client);
        }
        
        public string eliminar_cliente(int id_client) {
            return base.Channel.eliminar_cliente(id_client);
        }
        
        public System.Threading.Tasks.Task<string> eliminar_clienteAsync(int id_client) {
            return base.Channel.eliminar_clienteAsync(id_client);
        }
        
        public System.Data.DataSet ver_cliente() {
            return base.Channel.ver_cliente();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ver_clienteAsync() {
            return base.Channel.ver_clienteAsync();
        }
    }
}
