//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumirClienteWS.Producto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Producto.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name cod_p from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Crear_Producto_WS", ReplyAction="*")]
        ConsumirClienteWS.Producto.Crear_Producto_WSResponse Crear_Producto_WS(ConsumirClienteWS.Producto.Crear_Producto_WSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Crear_Producto_WS", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumirClienteWS.Producto.Crear_Producto_WSResponse> Crear_Producto_WSAsync(ConsumirClienteWS.Producto.Crear_Producto_WSRequest request);
        
        // CODEGEN: Generating message contract since element name cod_p from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar_Producto_WS", ReplyAction="*")]
        ConsumirClienteWS.Producto.Actualizar_Producto_WSResponse Actualizar_Producto_WS(ConsumirClienteWS.Producto.Actualizar_Producto_WSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar_Producto_WS", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumirClienteWS.Producto.Actualizar_Producto_WSResponse> Actualizar_Producto_WSAsync(ConsumirClienteWS.Producto.Actualizar_Producto_WSRequest request);
        
        // CODEGEN: Generating message contract since element name Eliminar_Producto_WSResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar_Producto_WS", ReplyAction="*")]
        ConsumirClienteWS.Producto.Eliminar_Producto_WSResponse Eliminar_Producto_WS(ConsumirClienteWS.Producto.Eliminar_Producto_WSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar_Producto_WS", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumirClienteWS.Producto.Eliminar_Producto_WSResponse> Eliminar_Producto_WSAsync(ConsumirClienteWS.Producto.Eliminar_Producto_WSRequest request);
        
        // CODEGEN: Generating message contract since element name Ver_Productos_WSResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ver_Productos_WS", ReplyAction="*")]
        ConsumirClienteWS.Producto.Ver_Productos_WSResponse Ver_Productos_WS(ConsumirClienteWS.Producto.Ver_Productos_WSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ver_Productos_WS", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumirClienteWS.Producto.Ver_Productos_WSResponse> Ver_Productos_WSAsync(ConsumirClienteWS.Producto.Ver_Productos_WSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Crear_Producto_WSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Crear_Producto_WS", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirClienteWS.Producto.Crear_Producto_WSRequestBody Body;
        
        public Crear_Producto_WSRequest() {
        }
        
        public Crear_Producto_WSRequest(ConsumirClienteWS.Producto.Crear_Producto_WSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Crear_Producto_WSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cod_p;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nom_pro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string marca_pro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string descri_pro;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public float prec_com;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public float prec_venta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string mat_pro;
        
        public Crear_Producto_WSRequestBody() {
        }
        
        public Crear_Producto_WSRequestBody(string cod_p, string nom_pro, string marca_pro, string descri_pro, float prec_com, float prec_venta, string mat_pro) {
            this.cod_p = cod_p;
            this.nom_pro = nom_pro;
            this.marca_pro = marca_pro;
            this.descri_pro = descri_pro;
            this.prec_com = prec_com;
            this.prec_venta = prec_venta;
            this.mat_pro = mat_pro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Crear_Producto_WSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Crear_Producto_WSResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirClienteWS.Producto.Crear_Producto_WSResponseBody Body;
        
        public Crear_Producto_WSResponse() {
        }
        
        public Crear_Producto_WSResponse(ConsumirClienteWS.Producto.Crear_Producto_WSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Crear_Producto_WSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Crear_Producto_WSResult;
        
        public Crear_Producto_WSResponseBody() {
        }
        
        public Crear_Producto_WSResponseBody(string Crear_Producto_WSResult) {
            this.Crear_Producto_WSResult = Crear_Producto_WSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Actualizar_Producto_WSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Actualizar_Producto_WS", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirClienteWS.Producto.Actualizar_Producto_WSRequestBody Body;
        
        public Actualizar_Producto_WSRequest() {
        }
        
        public Actualizar_Producto_WSRequest(ConsumirClienteWS.Producto.Actualizar_Producto_WSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Actualizar_Producto_WSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cod_p;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nom_pro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string marca_pro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string descri_pro;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public float prec_com;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public float prec_venta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string mat_pro;
        
        public Actualizar_Producto_WSRequestBody() {
        }
        
        public Actualizar_Producto_WSRequestBody(int id, string cod_p, string nom_pro, string marca_pro, string descri_pro, float prec_com, float prec_venta, string mat_pro) {
            this.id = id;
            this.cod_p = cod_p;
            this.nom_pro = nom_pro;
            this.marca_pro = marca_pro;
            this.descri_pro = descri_pro;
            this.prec_com = prec_com;
            this.prec_venta = prec_venta;
            this.mat_pro = mat_pro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Actualizar_Producto_WSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Actualizar_Producto_WSResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirClienteWS.Producto.Actualizar_Producto_WSResponseBody Body;
        
        public Actualizar_Producto_WSResponse() {
        }
        
        public Actualizar_Producto_WSResponse(ConsumirClienteWS.Producto.Actualizar_Producto_WSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Actualizar_Producto_WSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Actualizar_Producto_WSResult;
        
        public Actualizar_Producto_WSResponseBody() {
        }
        
        public Actualizar_Producto_WSResponseBody(string Actualizar_Producto_WSResult) {
            this.Actualizar_Producto_WSResult = Actualizar_Producto_WSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Eliminar_Producto_WSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Eliminar_Producto_WS", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirClienteWS.Producto.Eliminar_Producto_WSRequestBody Body;
        
        public Eliminar_Producto_WSRequest() {
        }
        
        public Eliminar_Producto_WSRequest(ConsumirClienteWS.Producto.Eliminar_Producto_WSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Eliminar_Producto_WSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public Eliminar_Producto_WSRequestBody() {
        }
        
        public Eliminar_Producto_WSRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Eliminar_Producto_WSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Eliminar_Producto_WSResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirClienteWS.Producto.Eliminar_Producto_WSResponseBody Body;
        
        public Eliminar_Producto_WSResponse() {
        }
        
        public Eliminar_Producto_WSResponse(ConsumirClienteWS.Producto.Eliminar_Producto_WSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Eliminar_Producto_WSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Eliminar_Producto_WSResult;
        
        public Eliminar_Producto_WSResponseBody() {
        }
        
        public Eliminar_Producto_WSResponseBody(string Eliminar_Producto_WSResult) {
            this.Eliminar_Producto_WSResult = Eliminar_Producto_WSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ver_Productos_WSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ver_Productos_WS", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirClienteWS.Producto.Ver_Productos_WSRequestBody Body;
        
        public Ver_Productos_WSRequest() {
        }
        
        public Ver_Productos_WSRequest(ConsumirClienteWS.Producto.Ver_Productos_WSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Ver_Productos_WSRequestBody {
        
        public Ver_Productos_WSRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ver_Productos_WSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ver_Productos_WSResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirClienteWS.Producto.Ver_Productos_WSResponseBody Body;
        
        public Ver_Productos_WSResponse() {
        }
        
        public Ver_Productos_WSResponse(ConsumirClienteWS.Producto.Ver_Productos_WSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Ver_Productos_WSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Ver_Productos_WSResult;
        
        public Ver_Productos_WSResponseBody() {
        }
        
        public Ver_Productos_WSResponseBody(string Ver_Productos_WSResult) {
            this.Ver_Productos_WSResult = Ver_Productos_WSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ConsumirClienteWS.Producto.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ConsumirClienteWS.Producto.WebService1Soap>, ConsumirClienteWS.Producto.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirClienteWS.Producto.Crear_Producto_WSResponse ConsumirClienteWS.Producto.WebService1Soap.Crear_Producto_WS(ConsumirClienteWS.Producto.Crear_Producto_WSRequest request) {
            return base.Channel.Crear_Producto_WS(request);
        }
        
        public string Crear_Producto_WS(string cod_p, string nom_pro, string marca_pro, string descri_pro, float prec_com, float prec_venta, string mat_pro) {
            ConsumirClienteWS.Producto.Crear_Producto_WSRequest inValue = new ConsumirClienteWS.Producto.Crear_Producto_WSRequest();
            inValue.Body = new ConsumirClienteWS.Producto.Crear_Producto_WSRequestBody();
            inValue.Body.cod_p = cod_p;
            inValue.Body.nom_pro = nom_pro;
            inValue.Body.marca_pro = marca_pro;
            inValue.Body.descri_pro = descri_pro;
            inValue.Body.prec_com = prec_com;
            inValue.Body.prec_venta = prec_venta;
            inValue.Body.mat_pro = mat_pro;
            ConsumirClienteWS.Producto.Crear_Producto_WSResponse retVal = ((ConsumirClienteWS.Producto.WebService1Soap)(this)).Crear_Producto_WS(inValue);
            return retVal.Body.Crear_Producto_WSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirClienteWS.Producto.Crear_Producto_WSResponse> ConsumirClienteWS.Producto.WebService1Soap.Crear_Producto_WSAsync(ConsumirClienteWS.Producto.Crear_Producto_WSRequest request) {
            return base.Channel.Crear_Producto_WSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirClienteWS.Producto.Crear_Producto_WSResponse> Crear_Producto_WSAsync(string cod_p, string nom_pro, string marca_pro, string descri_pro, float prec_com, float prec_venta, string mat_pro) {
            ConsumirClienteWS.Producto.Crear_Producto_WSRequest inValue = new ConsumirClienteWS.Producto.Crear_Producto_WSRequest();
            inValue.Body = new ConsumirClienteWS.Producto.Crear_Producto_WSRequestBody();
            inValue.Body.cod_p = cod_p;
            inValue.Body.nom_pro = nom_pro;
            inValue.Body.marca_pro = marca_pro;
            inValue.Body.descri_pro = descri_pro;
            inValue.Body.prec_com = prec_com;
            inValue.Body.prec_venta = prec_venta;
            inValue.Body.mat_pro = mat_pro;
            return ((ConsumirClienteWS.Producto.WebService1Soap)(this)).Crear_Producto_WSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirClienteWS.Producto.Actualizar_Producto_WSResponse ConsumirClienteWS.Producto.WebService1Soap.Actualizar_Producto_WS(ConsumirClienteWS.Producto.Actualizar_Producto_WSRequest request) {
            return base.Channel.Actualizar_Producto_WS(request);
        }
        
        public string Actualizar_Producto_WS(int id, string cod_p, string nom_pro, string marca_pro, string descri_pro, float prec_com, float prec_venta, string mat_pro) {
            ConsumirClienteWS.Producto.Actualizar_Producto_WSRequest inValue = new ConsumirClienteWS.Producto.Actualizar_Producto_WSRequest();
            inValue.Body = new ConsumirClienteWS.Producto.Actualizar_Producto_WSRequestBody();
            inValue.Body.id = id;
            inValue.Body.cod_p = cod_p;
            inValue.Body.nom_pro = nom_pro;
            inValue.Body.marca_pro = marca_pro;
            inValue.Body.descri_pro = descri_pro;
            inValue.Body.prec_com = prec_com;
            inValue.Body.prec_venta = prec_venta;
            inValue.Body.mat_pro = mat_pro;
            ConsumirClienteWS.Producto.Actualizar_Producto_WSResponse retVal = ((ConsumirClienteWS.Producto.WebService1Soap)(this)).Actualizar_Producto_WS(inValue);
            return retVal.Body.Actualizar_Producto_WSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirClienteWS.Producto.Actualizar_Producto_WSResponse> ConsumirClienteWS.Producto.WebService1Soap.Actualizar_Producto_WSAsync(ConsumirClienteWS.Producto.Actualizar_Producto_WSRequest request) {
            return base.Channel.Actualizar_Producto_WSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirClienteWS.Producto.Actualizar_Producto_WSResponse> Actualizar_Producto_WSAsync(int id, string cod_p, string nom_pro, string marca_pro, string descri_pro, float prec_com, float prec_venta, string mat_pro) {
            ConsumirClienteWS.Producto.Actualizar_Producto_WSRequest inValue = new ConsumirClienteWS.Producto.Actualizar_Producto_WSRequest();
            inValue.Body = new ConsumirClienteWS.Producto.Actualizar_Producto_WSRequestBody();
            inValue.Body.id = id;
            inValue.Body.cod_p = cod_p;
            inValue.Body.nom_pro = nom_pro;
            inValue.Body.marca_pro = marca_pro;
            inValue.Body.descri_pro = descri_pro;
            inValue.Body.prec_com = prec_com;
            inValue.Body.prec_venta = prec_venta;
            inValue.Body.mat_pro = mat_pro;
            return ((ConsumirClienteWS.Producto.WebService1Soap)(this)).Actualizar_Producto_WSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirClienteWS.Producto.Eliminar_Producto_WSResponse ConsumirClienteWS.Producto.WebService1Soap.Eliminar_Producto_WS(ConsumirClienteWS.Producto.Eliminar_Producto_WSRequest request) {
            return base.Channel.Eliminar_Producto_WS(request);
        }
        
        public string Eliminar_Producto_WS(int id) {
            ConsumirClienteWS.Producto.Eliminar_Producto_WSRequest inValue = new ConsumirClienteWS.Producto.Eliminar_Producto_WSRequest();
            inValue.Body = new ConsumirClienteWS.Producto.Eliminar_Producto_WSRequestBody();
            inValue.Body.id = id;
            ConsumirClienteWS.Producto.Eliminar_Producto_WSResponse retVal = ((ConsumirClienteWS.Producto.WebService1Soap)(this)).Eliminar_Producto_WS(inValue);
            return retVal.Body.Eliminar_Producto_WSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirClienteWS.Producto.Eliminar_Producto_WSResponse> ConsumirClienteWS.Producto.WebService1Soap.Eliminar_Producto_WSAsync(ConsumirClienteWS.Producto.Eliminar_Producto_WSRequest request) {
            return base.Channel.Eliminar_Producto_WSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirClienteWS.Producto.Eliminar_Producto_WSResponse> Eliminar_Producto_WSAsync(int id) {
            ConsumirClienteWS.Producto.Eliminar_Producto_WSRequest inValue = new ConsumirClienteWS.Producto.Eliminar_Producto_WSRequest();
            inValue.Body = new ConsumirClienteWS.Producto.Eliminar_Producto_WSRequestBody();
            inValue.Body.id = id;
            return ((ConsumirClienteWS.Producto.WebService1Soap)(this)).Eliminar_Producto_WSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirClienteWS.Producto.Ver_Productos_WSResponse ConsumirClienteWS.Producto.WebService1Soap.Ver_Productos_WS(ConsumirClienteWS.Producto.Ver_Productos_WSRequest request) {
            return base.Channel.Ver_Productos_WS(request);
        }
        
        public string Ver_Productos_WS() {
            ConsumirClienteWS.Producto.Ver_Productos_WSRequest inValue = new ConsumirClienteWS.Producto.Ver_Productos_WSRequest();
            inValue.Body = new ConsumirClienteWS.Producto.Ver_Productos_WSRequestBody();
            ConsumirClienteWS.Producto.Ver_Productos_WSResponse retVal = ((ConsumirClienteWS.Producto.WebService1Soap)(this)).Ver_Productos_WS(inValue);
            return retVal.Body.Ver_Productos_WSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirClienteWS.Producto.Ver_Productos_WSResponse> ConsumirClienteWS.Producto.WebService1Soap.Ver_Productos_WSAsync(ConsumirClienteWS.Producto.Ver_Productos_WSRequest request) {
            return base.Channel.Ver_Productos_WSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirClienteWS.Producto.Ver_Productos_WSResponse> Ver_Productos_WSAsync() {
            ConsumirClienteWS.Producto.Ver_Productos_WSRequest inValue = new ConsumirClienteWS.Producto.Ver_Productos_WSRequest();
            inValue.Body = new ConsumirClienteWS.Producto.Ver_Productos_WSRequestBody();
            return ((ConsumirClienteWS.Producto.WebService1Soap)(this)).Ver_Productos_WSAsync(inValue);
        }
    }
}
